
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseKey = import.meta.env.VITE_SUPABASE_KEY || '';

if (!supabaseUrl || !supabaseKey) {
  console.error('[Supabase] Missing URL or Key in environment variables');
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Add logging for all requests and responses
supabase.auth.onAuthStateChange((event, session) => {
  console.log(`[Supabase] Auth state changed: ${event}`, session);
});

// Note: We can't use .on() directly on supabase.from()
// Instead, we need to create a channel for realtime subscriptions
// This is just a simple log for now
console.log('[Supabase] Client initialized');

export { supabase };
