// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.REACT_APP_SUPABASE_URL || '';
const supabaseKey = process.env.REACT_APP_SUPABASE_KEY || '';

if (!supabaseUrl || !supabaseKey) {
  console.error('[Supabase] Missing URL or Key in environment variables');
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Add logging for all requests and responses
supabase.auth.onAuthStateChange((event, session) => {
  console.log(`[Supabase] Auth state changed: ${event}`, session);
});

supabase.from('*').on('*', (payload) => {
  console.log(`[Supabase] Realtime event:`, payload);
});

export { supabase };